baseURL = "https://codeverra.com/"
languageCode = "en-us"
title = "codeverra"
theme = "PaperMod"

enableRobotsTXT = true

[params]
  description = "Learn about learning Python, DSA, Machine Learning, and AI with clarity."
  defaultTheme = "auto"
  disableThemeToggle = false
  showToc = true
  tocOpen = true
  ShowReadingTime = true
  ShowWordCount = true
  [params.label]
    text = "codeverra"
    icon = "images/CODEVERRA.jpg"
    iconHeight = 32
    link = "/"

[[menu.main]]
  name = "Home"
  url = "/"
  weight = 1

[[menu.main]]
  name = "Courses"
  url = "/courses/"
  weight = 2

[[menu.main]]
  name = "About"
  url = "/about/"
  weight = 3

[[menu.main]]
  name = "Blogs"
  url = "/blogs/"
  weight = 4

[markup]
  [markup.goldmark]
    [markup.goldmark.renderer]
      unsafe = true






